2024-11-21 11:34:38,854 - train - ERROR - Error during training: config must be a dict or have a __dict__ attribute.
2024-11-21 11:41:19,837 - train - INFO - Preparing training data...
2024-11-21 11:41:19,894 - train - ERROR - Error during training: 'DataProcessor' object has no attribute 'create_knowledge_base'
2024-11-21 11:43:23,391 - train - INFO - Preparing training data...
2024-11-21 11:43:23,559 - train - INFO - Starting training...
2024-11-21 11:43:23,816 - train - ERROR - Error during training: The batch received was empty, your model won't be able to train on it. Double-check that your training dataset contains keys expected by the model: input_ids,past_key_values,attention_mask,token_type_ids,position_ids,head_mask,inputs_embeds,encoder_hidden_states,encoder_attention_mask,labels,use_cache,output_attentions,output_hidden_states,return_dict,label,label_ids,labels.
2024-11-21 11:46:29,708 - train - INFO - Preparing training data...
2024-11-21 11:46:29,723 - train - ERROR - Error during training: 'DataProcessor' object has no attribute 'load_datasets'
2024-11-21 11:49:05,184 - train - INFO - Preparing training data...
2024-11-21 11:49:06,127 - train - INFO - Starting training...
